---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kangooweb-deployment
#  namespace: aks-hackaton-paris
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: kangooweb
    spec:
      containers:
      - name: kangooweb
        image: kangooroo.azurecr.io/kangoogoweb-linux:latest
        ports:
        - containerPort: 80
        env:
        - name: LISTENINGPORT
          value: ":80-unused value"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kangooweb-svc
#  namespace: aks-hackaton-paris
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kangooweb