apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kangooweb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: kangooweb
    spec:
      containers:
      - name: kangooweb
        image: kangooroo.azurecr.io/kangoogoweb-linux:latest
        ports:
        - containerPort: 8080
        env:
        - name: LISTENINGPORT
          value: ":8080"
---
apiVersion: v1
kind: Service
metadata:
  name: kangooweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kangooweb
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kangooweb
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: kangooweb.53274ffb-313e-4b78-a107-a7759a3b1a49.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: kangooweb
          servicePort: 80
        path: /

